### ISSUE TITLE
global install error

### ISSUE THREAD

**Issue by ggascoigne** [cdaringe/ripcord#57]
14:17 $ sudo npm i -g ripcord
Password:
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
/usr/local/bin/ripcord -> /usr/local/lib/node_modules/ripcord/bin/ripcord.js

> ripcord@0.22.1 install /usr/local/lib/node_modules/ripcord
> node bin/ripcord.js counsel apply

error: [ripcord] Unable to find a package.json for this project
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "i" "-g" "ripcord"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! ripcord@0.22.1 install: `node bin/ripcord.js counsel apply`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ripcord@0.22.1 install script 'node bin/ripcord.js counsel apply'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ripcord package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/ripcord.js counsel apply
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ripcord
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ripcord
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ggp/dev/tw-git/console/ui/npm-debug.log

**Comment by cdaringe** [comment]
fixed in 0.22.2. it's hacky, but it works ;)
